---
#
# use release-please as a GitHub App
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please
# -> marked as deprecated, EOL: August 2025
handleGHRelease: true
manifest: true
# config-file: .github/release-please-config.json
# manifest-file: .github/release-please-manifest.json
